const http = require('http'); // built-in module
const fs = require('fs'); // built-in
//const {random} = require('lodash'); // node_modules folder

const server = http.createServer((request, response) => {
    const stream = fs.createReadStream("./src/lib.js");
    // data, error, end are events generated by "stream"
    stream.on("data", (chunk) => {
        response.write(chunk.toString()); // can execute multiple times based on size of file
    });

    stream.on("end", () => {
        // stream next episode
        response.end();
    })
});

server.listen(1234, () => console.log("server started!!!"));

